apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%  # Max pods qui peuvent être indisponibles pendant la mise à jour
      maxSurge: 1          # Nombre maximal de pods supplémentaires pendant la mise à jour
  minReadySeconds: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: petclinic-app
  template:
    metadata:
      labels:
        app: petclinic-app
    spec:
      containers:
      - name: petclinic-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: '1'
            memory: '1G'
          requests:
            cpu: '1'
            memory: '1G'
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
