{{- if .Values.serviceAccount.create -}}
# Création d'un ServiceAccount pour l'application Petclinic
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "petclinic.serviceAccountName" . }}
  labels:
{{ include "petclinic.labels" . | indent 4 }}
{{- end -}}
